#!/usr/bin/env python3
"""Gzip material_database.json into a PROGMEM C header for the firmware default DB.

Usage:
    .venv/bin/python tools/gen_db_header.py [input.json] [output.h]

Defaults: material_database.json -> firmware/src/material_db_default.h
The firmware serves this gzipped blob directly (Content-Encoding: gzip) until the
user uploads a replacement or pulls one from the printer.
"""
import gzip
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "material_database.json"
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "firmware" / "src" / "material_db_default.h"

    raw = src.read_bytes()
    # Validate it parses and has the expected Creality shape before shipping it.
    doc = json.loads(raw)
    items = doc["result"]["list"]
    if not items or "base" not in items[0]:
        raise SystemExit("unexpected DB shape: result.list[].base missing")

    # Re-serialize compactly so the PROGMEM blob is as small as possible.
    compact = json.dumps(doc, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    blob = gzip.compress(compact, mtime=0)

    dst.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// AUTO-GENERATED by tools/gen_db_header.py - do not edit by hand.",
        f"// source: {src.name}  items: {len(items)}  raw: {len(compact)}B  gz: {len(blob)}B",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"static const size_t MATERIAL_DB_DEFAULT_LEN = {len(blob)};",
        "static const uint8_t MATERIAL_DB_DEFAULT[] PROGMEM = {",
    ]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        lines.append("  " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    dst.write_text("\n".join(lines) + "\n")

    print(f"wrote {dst.relative_to(ROOT)}  ({len(items)} items, {len(compact)} -> {len(blob)} bytes gz)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
